name: fossa
on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  fossa-scan:
    # Don't attempt to run FOSSA on forks
    if: github.repository_owner == 'spinframework'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1.7.0
        with:
          api-key: d21f74dd762b95fa3e318b70e8428ca5 # This is a push-only token that is safe to be exposed
